### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by IEEEAPSIT** [IEEE-APSIT/IEEE-Website#2]
@all-contributors please add @nikita24383  for mentoring

**Comment by IEEEAPSIT** [comment]
@all-contributors please add @nikita24383  for mentoring

**Comment by IEEEAPSIT** [comment]
@all-contributors please add @nikita24383 for projectManagement

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for mentoring

**Comment by nikita24383** [comment]
@all-contributors please add @sbangale for design

**Comment by nikita24383** [comment]
@all-contributors please add @AmrutaKoshe for design

**Comment by nikita24383** [comment]
@all-contributors please add @sejalkhedekar for design

**Comment by nikita24383** [comment]
@all-contributors please add @kshitizJ for design

**Comment by nikita24383** [comment]
@all-contributors please add @AaryanParab for design

**Comment by nikita24383** [comment]
@all-contributors please add @Omichougule for design

**Comment by nikita24383** [comment]
@all-contributors please add @ishaphadkar for design

**Comment by nikita24383** [comment]
@all-contributors please add @Sid616 for design

**Comment by nikita24383** [comment]
@all-contributors please add @MansiShah15 for design

**Comment by nikita24383** [comment]
@all-contributors please add @rakshitshah-28 for design

**Comment by IEEEAPSIT** [comment]
@all-contributors please add @rakshitshah-28 for projectManagement

**Comment by IEEEAPSIT** [comment]
@all-contributors please add @YashSampat23154 for mentoring

**Comment by IEEEAPSIT** [comment]
@all-contributors please add @YashSampat23154 for projectManagement

**Comment by IEEEAPSIT** [comment]
@all-contributors add @utkarsh17naik for design

**Comment by IEEEAPSIT** [comment]
@all-contributors add @adi123567 for design

**Comment by nikita24383** [comment]
@all-contributors add @AaryanParab for design

**Comment by nikita24383** [comment]
@all-contributors add @Prathamesh247  for montering

**Comment by nikita24383** [comment]
@all-contributors add @Prathamesh247 for projectManagement
